# Generated by Django 5.0.6 on 2024-05-18 10:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user_name', models.CharField(max_length=200)),
                ('contact_no', models.IntegerField(max_length=10)),
                ('address', models.TextField(blank=True, max_length=1000, null=True)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
