# Generated by Django 5.0.6 on 2024-05-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xircls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='contact_no',
            field=models.CharField(max_length=15),
        ),
    ]
